name: Generate languages card

on:
  schedule:
    - cron: "23 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate languages.svg (light)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=default&hide_border=false
          path: dist-light/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate languages.svg (dark)
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=dracula&hide_border=false
          path: dist-dark/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push light languages to languages-output-light
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: languages-output-light
          build_dir: dist-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push dark languages to languages-output-dark
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: languages-output-dark
          build_dir: dist-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
