name: Generate snake animation

on:
  schedule:
    - cron: "31 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist-light/snake.svg?palette=github-light
            dist-dark/snake.svg?palette=github-dark

      - name: push light snake to snake-output-light
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-output-light
          build_dir: dist-light
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push dark snake to snake-output-dark
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-output-dark
          build_dir: dist-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
